#cloud-config
# vim: syntax=yaml

# Assure this file is a correct cloud init with
#   cloud-init schema -c thisfile.yml

# Yaml check this file with
#   yamllint  thisfile.yml

# For detailed info on modules:
# http://cloudinit.readthedocs.io/en/latest/topics/modules.html

# use keywork MY_HOSTNAME (will be replaced by my script)

hostname: my_hostname
manage_etc_hosts: true
# disable root ssh
disable_root: true
fqdn: my_hostname.my_domain
timezone: Europe/Rome
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa9Rib5xmP+bAd+JC5zM1EK5RsAtYk6cYX+h++UUdj3 dante-ed25519@laptop
chpasswd:
  expire: false

mounts:
  - ['/dev/sdb1', '/var/nfs-share']

# mount_default_fields
# These values are used to fill in any entries in 'mounts' that are not
# complete.  This must be an array, and must have 7 fields.
mount_default_fields: [None, None, "auto", "defaults,nofail", "0", "2"]

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: true

# setup the file system on the device
fs_setup:
  - label: nfs
    filesystem: ext4
    device: /dev/sdb
    partition: auto
    overwrite: true

# apt_pipelining (configure Acquire::http::Pipeline-Depth)
# Default: disables HTTP pipelining. Certain web servers, such
# as S3 do not pipeline properly (LP: #948461).
apt_pipelining: false

# Upgrade the instance on first boot
package_upgrade: true
package_update: true
package_reboot_if_required: true

# Install the following packages
# (keep alphabetical order)
packages:
  - aptitude
  - apt-utils
  - bash-completion
  - btop
  - byobu
  - bzip2
  - ca-certificates
  - cifs-utils
  - colordiff
  - cron
  - ctop
  - curl
  - dnsutils
  - figlet
  - git
  - htop
  - httpie
  - iftop
  - iotop
  - jq
  - lsb-release
  - mc
  - mlocate
  - ncdu
  - neofetch
  - net-tools
  - nfs-kernel-server
  - nmap
  - plocate
  - pwgen
  - qemu-guest-agent
  - rsync
  - screen
  - sysfsutils
  - tar
  - tree
  - unattended-upgrades
  - unzip
  - vim
  - wget
  - whois
  - wireguard
  - yamllint
  - zip

groups:
  - users

users:
  - default
  - name: remote
    # generated with: mkpasswd --method=SHA-512 --rounds=4096
    passwd: $6$rounds=4096$8mprvMT/jbOzH.bh$YWArz.2Uk1jX7dSiI0RlqfL8Arc4vcypL3wBWb7ePazGfEKBhzC9YIdAF8NP90dC7GkdjUly9b5UEDbEHvhrx.
    # do not prevents the user from changing their password
    lock_passwd: false
  - name: dante
    gecos: Dante
    primary_group: users
    groups: admin
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa9Rib5xmP+bAd+JC5zM1EK5RsAtYk6cYX+h++UUdj3 dante-ed25519@laptop

runcmd:
  - mkdir /var/nfs-share
  # - chgrp users /var/nfs-share
  - chmod 775 /var/nfs-share
  - mkdir /StorageBox
  - chmod 02775 /StorageBox
  - systemctl restart qemu-guest-agent
  - apt purge -y  popularity-contest
  - apt -y autoremove
  # remove Ubuntu trash
  - sed -i 's/^ENABLED=.*/ENABLED=0/' /etc/default/motd-news
  # remove snapd trash
  - snap remove lxd
  - snap remove core20
  - snap remove snapd
  - systemctl stop snapd.service
  - systemctl stop snapd.socket
  - systemctl stop snapd.seeded.service
  - systemctl disable snapd.service
  - systemctl disable snapd.socket
  - systemctl disable snapd.seeded.service
  - systemctl stop snapd.service
  - systemctl stop snapd.socket
  - systemctl stop snapd.seeded.service
  - rm -rf /var/cache/snapd/
  - apt autoremove --purge snapd -y
  - rm -rf /root/snap
  # remove apport trash
  - systemctl stop apport
  - sed -i 's/^enabled=.*/enabled=0/' /etc/default/apport
  - systemctl disable apport.service
  - systemctl mask apport.service
  - rm -rf /etc/cron.daily/apport
  - rm -rf /var/crash/*
  # disable updatedb from scanning /var/nfs-share
  - sed -i 's/PRUNEPATHS="/&\/var\/nfs-share /' /etc/updatedb.conf
  # disable updatedb from scanning /StorageBox
  - sed -i 's/PRUNEPATHS="/&\/StorageBox /' /etc/updatedb.conf
  # to avoid perl errors on locale
  - locale-gen "en_US.UTF-8"
  - update-alternatives --set editor /usr/bin/vim.basic
  # Hetzner CIFS storagebox
  - apt install linux-modules-extra-$(uname -r) -y
  - mount -a
  - exportfs -arvf
  - systemctl start nfs-kernel-server
  - systemctl enable nfs-kernel-server


# Write arbitrary files on filesystem
write_files:
  - content: |
      alias ll='ls -la'
      alias cd..='cd ..'
      alias vi=vim
      alias svi='sudo vi'
      alias vis='vim "+set si"'

      alias rm='rm -i'
      alias mv='mv -i'
      alias cp='cp -i'

      alias sha1='openssl sha1'
      alias grep='grep --color=auto'
      alias pwgen='pwgen --no-vowels --numerals --capitalize --ambiguous --secure'
      alias free='\free -mht'
      alias sudo='\sudo '
      alias dmesg='\dmesg --color=auto --reltime --human --nopager --decode'
    path: /etc/profile.d/bash-aliases.sh
    permissions: '0644'
  - content: |
      set modeline
      set tabstop=4
      set shiftwidth=4
      filetype plugin indent off
      filetype plugin off
      syntax on
      " replace TAB with spaces before saving
      autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab fileencoding=utf-8
      autocmd FileType bash setlocal ts=2 sts=2 sw=2 expandtab fileencoding=utf-8
      autocmd FileType json setlocal ts=2 sts=2 sw=2 expandtab fileencoding=utf-8
      " remove trailing spaces before saving
      autocmd BufWritePre * :%s/\s\+$//e
    path: /etc/vim/vimrc.local
  - content: |
      username=SMB_USERNAME
      password=SMB_PASSWORD
    path: /etc/smb-credentials.txt
    permissions: '0600'
  - content: |
      # mount CIFS https://docs.hetzner.com/robot/storage-box/access/access-samba-cifs
      //SMB_USERNAME.your-storagebox.de/backup /StorageBox cifs iocharset=utf8,rw,credentials=/etc/smb-credentials.txt,uid=1001,gid=100,file_mode=0600,dir_mode=0770 0 0
    path: /etc/fstab
    append: true
  - content: |
      #!/bin/sh
      # assure we have the proper linux-modules-extra installed
      # even after the upgrade of the kernel
      apt update
      apt install linux-modules-extra-$(uname -r) -y
    path: /var/lib/cloud/scripts/per-boot/install_linux-modules-extra.sh
    permissions: '0700'
  - content: |
      /var/nfs-share *(rw,sync,no_root_squash,no_subtree_check)
    path: /etc/exports
    append: true
  - content: |
      # allow forwarding traffic for this VM to be a gateway
      # (it will be a wireguard connected to mullvad)
      net.ipv4.ip_forward=1
    path: /etc/sysctl.conf
    append: true
  - content: |
      # Get the following from mullvad (expire 13 Aug 2024)
      [Interface]
      # Device: Speedy Camel
      PrivateKey = xxxxxxxxx
      Address = x.x.x.x/32
      #  DNS = x.x.x.x
      ####################################################
      # iptables firewall rules                          #
      ####################################################
      #    We enable I/O traffic for the VPN virtual interface: wg0
      PostUp   = iptables -A FORWARD --in-interface  wg0 -j ACCEPT
      PostUp   = iptables -A FORWARD --out-interface wg0 -j ACCEPT
      # allow peers to surf the internet using mullvad
      PostUp   = iptables -t nat -A POSTROUTING --source 10.10.10.0/24 --out-interface mullvad -j MASQUERADE
      PostDown = iptables -t nat -D POSTROUTING --source 10.10.10.0/24 --out-interface mullvad -j MASQUERADE

      [Peer]
      PublicKey = xxxxxxxxxxxxxxxxxxxxxxxx
      AllowedIPs = 0.0.0.0/0
      Endpoint = x.x.x.x:3284
    path: /etc/wireguard/mullvad.conf


# Echo the following message when finished without errors
final_message: "===> cloud-init finished his job at $TIMESTAMP, after $UPTIME seconds"
