#cloud-config
# vim: syntax=yaml

# Assure this file is a correct cloud init with
#   cloud-init schema -c thisfile.yml

# Yaml check this file with
#   yamllint  thisfile.yml

# For detailed info on modules:
# http://cloudinit.readthedocs.io/en/latest/topics/modules.html

# use keywork MY_HOSTNAME (will be replaced by my script)

hostname: my_hostname
manage_etc_hosts: true
# disable root ssh
disable_root: true
fqdn: my_hostname.my_domain
timezone: Europe/Rome
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa9Rib5xmP+bAd+JC5zM1EK5RsAtYk6cYX+h++UUdj3 dante-ed25519@laptop
chpasswd:
  expire: false

mounts:
  - ['/dev/sdb1', '/var/lib/docker']

# mount_default_fields
# These values are used to fill in any entries in 'mounts' that are not
# complete.  This must be an array, and must have 7 fields.
mount_default_fields: [None, None, "auto", "defaults,nofail", "0", "2"]

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: true

# setup the file system on the device
fs_setup:
  - label: docker
    filesystem: ext4
    device: /dev/sdb
    partition: auto
    overwrite: true

# apt_pipelining (configure Acquire::http::Pipeline-Depth)
# Default: disables HTTP pipelining. Certain web servers, such
# as S3 do not pipeline properly (LP: #948461).
apt_pipelining: false

# Add apt resources
apt:
  sources:
    docker:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
      keyid: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    youtube-downloader:
      # https://github.com/yt-dlp/yt-dlp/wiki/Installation
      source: "ppa:tomtomtom/yt-dlp"
      keyid: "CEC312CC5ED8215A6E0EFC49B90E9186F0E836FB"

# Upgrade the instance on first boot
package_upgrade: true
package_update: true
package_reboot_if_required: true

# Install the following packages
# (keep alphabetical order)
packages:
  - aptitude
  - apt-utils
  - bash-completion
  - btop
  - byobu
  - bzip2
  - ca-certificates
  - cifs-utils
  - colordiff
  - cron
  - ctop
  - curl
  - dnsutils
  - docker-ce
  - figlet
  - git
  - htop
  - httpie
  - iftop
  - iotop
  - jq
  - lsb-release
  - mc
  - mlocate
  - ncdu
  - neofetch
  - net-tools
  - nfs-common
  - nmap
  - plocate
  - pwgen
  - qemu-guest-agent
  - rsync
  - screen
  - sysfsutils
  - speedtest-cli
  - software-properties-common
  - tar
  - tree
  - unattended-upgrades
  - unzip
  - vim
  - wget
  - whois
  - yamllint
  - yt-dlp
  - zip

groups:
  - users

users:
  - default
  - name: remote
    # generated with: mkpasswd --method=SHA-512 --rounds=4096
    passwd: $6$rounds=4096$8mprvMT/jbOzH.bh$YWArz.2Uk1jX7dSiI0RlqfL8Arc4vcypL3wBWb7ePazGfEKBhzC9YIdAF8NP90dC7GkdjUly9b5UEDbEHvhrx.
    # do not prevents the user from changing their password
    lock_passwd: false
  - name: dante
    gecos: Dante
    primary_group: users
    groups: admin, docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa9Rib5xmP+bAd+JC5zM1EK5RsAtYk6cYX+h++UUdj3 dante-ed25519@laptop

runcmd:
  - mkdir /srv
  - chgrp users /srv
  - chmod 02775 /srv
  # requisiti redis, mongo, etc...
  - sysctl vm.overcommit_memory=1
  - echo 'vm.overcommit_memory = 1' >>  /etc/sysctl.conf
  - sysctl -w net.core.somaxconn=65535
  - echo 'net.core.somaxconn = 65535' >>  /etc/sysctl.conf
  - echo never > /sys/kernel/mm/transparent_hugepage/enabled
  # il seguente necessita di pacchetto sysfsutils
  - echo 'kernel/mm/transparent_hugepage/enabled = never' >> /etc/sysfs.conf
  # requisito elasticsearch
  - echo 'vm.max_map_count = 262144' >>  /etc/sysctl.conf
  - sysctl -w vm.max_map_count=262144
  - systemctl restart qemu-guest-agent
  - apt purge -y  popularity-contest
  - apt -y autoremove
  # remove Ubuntu trash
  - sed -i 's/^ENABLED=.*/ENABLED=0/' /etc/default/motd-news
  # remove snapd trash
  - snap remove lxd
  - snap remove core20
  - snap remove snapd
  - systemctl stop snapd.service
  - systemctl stop snapd.socket
  - systemctl stop snapd.seeded.service
  - systemctl disable snapd.service
  - systemctl disable snapd.socket
  - systemctl disable snapd.seeded.service
  - systemctl stop snapd.service
  - systemctl stop snapd.socket
  - systemctl stop snapd.seeded.service
  - rm -rf /var/cache/snapd/
  - apt autoremove --purge snapd -y
  - rm -rf /root/snap
  # remove apport trash
  - systemctl stop apport
  - sed -i 's/^enabled=.*/enabled=0/' /etc/default/apport
  - systemctl disable apport.service
  - systemctl mask apport.service
  - rm -rf /etc/cron.daily/apport
  - rm -rf /var/crash/*
  # disable updatedb from scanning /var/lib/docker
  - sed -i 's/PRUNEPATHS="/&\/var\/lib\/docker /' /etc/updatedb.conf
  # to avoid perl errors on locale
  - locale-gen "en_US.UTF-8"
  - update-alternatives --set editor /usr/bin/vim.basic
  # Hetzner CIFS storagebox
  # - apt install linux-modules-extra-$(uname -r) -y
  - mount -a
  # for keepalived
  - modprobe ip_vs
  - systemctl restart systemd-journald.service
  # more
  - ln -s /srv/stack/bin/deploy /usr/local/bin/deploy
  - curl -o /usr/local/bin/docker-stack-ps https://gitlab.com/opencity-labs/swarm-utils/-/raw/main/docker-stack-ps && chmod +x /usr/local/bin/docker-stack-ps
  - curl -o /usr/local/bin/today-filter-docker-ps https://gitlab.com/opencity-labs/swarm-utils/-/raw/main/today-filter-docker-ps && chmod +x /usr/local/bin/today-filter-docker-ps
  - wget https://gitlab.com/opencity-labs/provisioning/-/raw/main/cloud-init-scripts/vimrc.local_for_managers -O /etc/vim/vimrc.local
  # install vim plugin manager and plugins
  - mkdir /root/cancellami
  - wget https://gitlab.com/opencity-labs/provisioning/-/raw/main/cloud-init-scripts/vim_plugins/add_vim_plugins.sh -O /root/cancellami/add_vim_plugins.sh && bash /root/cancellami/add_vim_plugins.sh
  # configurazioni yamllint
  - wget https://gitlab.com/opencity-labs/provisioning/-/raw/main/cloud-init-scripts/yamllint/yamllint.yaml -O /etc/default/yamllint.yaml


# Write arbitrary files on filesystem
write_files:
  - content: |
      alias ll='ls -la'
      alias cd..='cd ..'
      alias vi=vim
      alias svi='sudo vi'
      alias vis='vim "+set si"'

      alias rm='rm -i'
      alias mv='mv -i'
      alias cp='cp -i'

      alias sha1='openssl sha1'
      alias grep='grep --color=auto'
      alias pwgen='pwgen --no-vowels --numerals --capitalize --ambiguous --secure'
      alias free='\free -mht'
      alias sudo='\sudo '
      alias dmesg='\dmesg --color=auto --reltime --human --nopager --decode'
    path: /etc/profile.d/bash-aliases.sh
    permissions: '0644'
  - content: |
      set modeline
      set tabstop=4
      set shiftwidth=4
      filetype plugin indent off
      filetype plugin off
      syntax on
      " replace TAB with spaces before saving
      autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab fileencoding=utf-8
      autocmd FileType bash setlocal ts=2 sts=2 sw=2 expandtab fileencoding=utf-8
      autocmd FileType json setlocal ts=2 sts=2 sw=2 expandtab fileencoding=utf-8
      " remove trailing spaces before saving
      autocmd BufWritePre * :%s/\s\+$//e
    path: /etc/vim/vimrc.local
  - content: |
      ---
      # see `man yamllint`
      # relax some rules
      extends: default
      rules:
        line-length: disable
    path: /etc/default/yamllint.yaml
  - content: |
      # yamllint conf file
      YAMLLINT_CONFIG_FILE=/etc/default/yamllint.yaml
    path: /etc/environment
    append: true
  - content: |
      #!/bin/sh
      # periodically cleanup of images not used
      /usr/bin/docker system prune --force --all
    path: /etc/cron.daily/docker-cleanup
    permissions: '0755'
  - content: |
      username=SMB_USERNAME
      password=SMB_PASSWORD
    path: /etc/smb-credentials.txt
    permissions: '0600'
  - content: |
      #!/bin/sh
      # assure we have the proper linux-modules-extra installed
      # even after the upgrade of the kernel
      apt update
      apt install linux-modules-extra-$(uname -r) -y
    path: /var/lib/cloud/scripts/per-boot/install_linux-modules-extra.sh
    permissions: '0700'
  - content: |
      # https://geek-cookbook.funkypenguin.co.nz/docker-swarm/keepalived/
      modprobe ip_vs
    path: /etc/modules
    append: true
  - content: |
      #!/bin/bash
      docker run -d --name keepalived --restart=always \
      --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW --net=host \
      -e KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['10.10.10.201', '10.10.10.202', '10.10.10.203']" \
      -e KEEPALIVED_VIRTUAL_IPS=10.10.10.200 \
      -e KEEPALIVED_PRIORITY=200 \
      osixia/keepalived:2.0.20
    path: /root/docker-run-keepalived-master.sh
    permissions: '0700'
  - content: |
      #!/bin/bash
      docker run -d --name keepalived --restart=always \
      --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW --net=host \
      -e KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['10.10.10.201', '10.10.10.202', '10.10.10.203']" \
      -e KEEPALIVED_VIRTUAL_IPS=10.10.10.200 \
      -e KEEPALIVED_PRIORITY=100 \
      osixia/keepalived:2.0.20
    path: /root/docker-run-keepalived.sh
    permissions: '0700'
  - content: |
      NFS_SERVER_IP:/var/nfs-share  /srv nfs defaults,_netdev  0 0
    path: /etc/fstab
    append: true
  - content: |
      # limit the size of journald or else is 4G
      SystemMaxUse=500M
    path: /etc/systemd/journald.conf
    append: true

# Echo the following message when finished without errors
final_message: "===> cloud-init finished his job at $TIMESTAMP, after $UPTIME seconds"
